### ISSUE TITLE
Static methods should not be called with $this

### ISSUE THREAD

**Issue by lord2800** [Evertt/Slade#15]
This is all over the tests. You should be calling static methods with `self`, `static`, or `ClassName`. `$this` only applies to instance methods. You might want to try not having static methods at all--it may result in a better experience overall.

**Comment by Evertt** [comment]
Even though it made no difference to the functionality, I changed it because I agree that it's more correct. I don't understand people's dislike towards static methods though. Could you explain your preference for non-static methods?

My preference for static methods in this library is because there is no need (AFAIK) to make separate instances of Slade.

**Comment by lord2800** [comment]
Generally speaking, it's easier to test non-static things than it is static things. In your case, it might be overkill--but imagine if I have two separate paths that I want to render templates from, and I don't want to mix the two at all (say, one is trusted code I wrote and another is untrusted code from the user that I'm going to filter in other ways before it goes out to the browser). As it stands, doing that would involve resetting `Slade::$templatePaths` every time I call `Slade::parse` currently. That's cumbersome at best, and confusing at worst. Making `Slade` and its related classes non-static would allow that trivially.

**Comment by Evertt** [comment]
Hmm, I wonder if that use case is very likely to happen. I'll leave it for now, but I'll change it if I get more requests about this.
